apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: auth-service
spec:
  destination:
    namespace: auth-service
    server: https://kubernetes.default.svc
  source:
    path: app
    repoURL: https://github.com/the-coding-carrot/devops-lecture-project
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
      enabled: true
    syncOptions:
      - CreateNamespace=true
