apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkout-service
  labels:
    app: checkout
spec:
  replicas: 8
  selector:
    matchLabels:
      app: checkout
  template:
    metadata:
      labels:
        app: checkout
    spec:
      containers:
      - name: checkout-service
        image: crmsn/checkout-service:latest
        ports:
        - containerPort: 8080