apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  labels:
    app: product
spec:
  replicas: 10
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
      - name: product-service
        image: crmsn/product-service:latest
        ports:
        - containerPort: 8080